import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1766055164232 implements MigrationInterface {
    name = 'InitialSchema1766055164232'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`club_schedule\` (\`id\` int NOT NULL AUTO_INCREMENT, \`clubId\` int NOT NULL, \`categoryId\` int NOT NULL, \`startDate\` datetime NOT NULL, \`endDate\` datetime NOT NULL, \`place\` varchar(255) NOT NULL, \`title\` varchar(255) NOT NULL, \`content\` text NULL, \`maxAttendee\` int NOT NULL DEFAULT '0', \`type\` enum ('FREE', 'PAID') NOT NULL, \`price\` int NULL DEFAULT '0', \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), \`updatedAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`club_schedule_member\` (\`id\` int NOT NULL AUTO_INCREMENT, \`scheduleId\` int NOT NULL, \`memberId\` int NOT NULL, \`status\` enum ('ATTEND', 'CANCEL') NOT NULL DEFAULT 'ATTEND', \`paid\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`club_member\` (\`id\` int NOT NULL AUTO_INCREMENT, \`clubId\` int NOT NULL, \`userId\` int NOT NULL, \`status\` enum ('JOIN', 'WAIT') NOT NULL, \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`club_ban_member\` (\`id\` int NOT NULL AUTO_INCREMENT, \`clubId\` int NOT NULL, \`banUserId\` int NOT NULL, \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`club_chat_room_member\` (\`id\` int NOT NULL AUTO_INCREMENT, \`roomId\` varchar(255) NOT NULL, \`userId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`club_chat_room\` (\`id\` varchar(36) NOT NULL, \`clubId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`club\` (\`id\` int NOT NULL AUTO_INCREMENT, \`leaderId\` int NOT NULL, \`clubName\` varchar(255) NOT NULL, \`categoryId\` int NOT NULL, \`introduction\` varchar(255) NOT NULL, \`region\` varchar(255) NULL, \`lat\` decimal(8,6) NULL, \`lng\` decimal(9,6) NULL, \`type\` enum ('FREE', 'PAID') NOT NULL, \`joinMode\` enum ('AUTO', 'APPROVAL') NOT NULL DEFAULT 'AUTO', \`status\` enum ('ACTIVE', 'PAUSE', 'DELETED', 'AWAITING') NOT NULL DEFAULT 'ACTIVE', \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), \`updatedAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP, \`userId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`category\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`type\` enum ('NORMAL', 'HUB') NOT NULL DEFAULT 'NORMAL', \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), UNIQUE INDEX \`IDX_4bb3fbb86fb58fe2de057ea32a\` (\`name\`, \`type\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`comment_like\` (\`id\` int NOT NULL AUTO_INCREMENT, \`commentId\` int NOT NULL, \`userId\` int NOT NULL, \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`comment\` (\`id\` int NOT NULL AUTO_INCREMENT, \`postId\` int NOT NULL, \`userId\` int NOT NULL, \`content\` text NOT NULL, \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), \`updatedAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP, \`likeCount\` int NOT NULL DEFAULT '0', \`parentCommentId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`post_like\` (\`id\` int NOT NULL AUTO_INCREMENT, \`postId\` int NOT NULL, \`userId\` int NOT NULL, \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`post_saved\` (\`id\` int NOT NULL AUTO_INCREMENT, \`postId\` int NOT NULL, \`userId\` int NOT NULL, \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`post\` (\`id\` int NOT NULL AUTO_INCREMENT, \`categoryId\` int NOT NULL, \`userId\` int NOT NULL, \`title\` varchar(255) NOT NULL, \`region\` varchar(255) NOT NULL, \`content\` text NOT NULL, \`isPublic\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), \`updatedAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP, \`commentCount\` int NOT NULL DEFAULT '0', \`likeCount\` int NOT NULL DEFAULT '0', \`shareCount\` int NOT NULL DEFAULT '0', \`status\` int NOT NULL DEFAULT '1', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`senior_content\` (\`id\` int NOT NULL AUTO_INCREMENT, \`adminId\` int NOT NULL, \`title\` varchar(255) NULL, \`content\` text NULL, \`categoryId\` int NOT NULL, \`status\` int NULL DEFAULT '0', \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), \`updatedAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`point_history\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`paymentId\` int NULL, \`use\` varchar(255) NULL, \`charge\` varchar(255) NULL, \`changes\` int NULL, \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`chat_room\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`chat_room_user\` (\`id\` int NOT NULL AUTO_INCREMENT, \`roomId\` varchar(255) NOT NULL, \`userId\` int NOT NULL, \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_suspension\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`reportedCount\` int NOT NULL, \`suspendedAt\` datetime NOT NULL, \`suspendedUntil\` datetime NOT NULL, \`releasedAt\` datetime NULL, \`status\` enum ('ACTIVE', 'RELEASED') NOT NULL DEFAULT 'ACTIVE', \`reason\` text NULL, \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), \`updatedAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`loginEmail\` varchar(255) NOT NULL, \`hashedPassword\` varchar(255) NOT NULL, \`phoneNumber\` varchar(255) NOT NULL, \`nickname\` varchar(255) NULL, \`profileImageUrl\` varchar(255) NULL, \`zipCode\` varchar(255) NULL, \`roadAddress\` varchar(255) NULL, \`detailAddress\` varchar(255) NULL, \`lat\` decimal(8,6) NULL, \`lng\` decimal(9,6) NULL, \`favoriteCategory\` varchar(255) NULL, \`introduction\` varchar(255) NULL, \`gender\` enum ('MAN', 'WOMAN') NULL, \`birthDate\` date NULL, \`region\` varchar(255) NULL, \`role\` enum ('USER', 'ADMIN') NOT NULL DEFAULT 'USER', \`status\` int NOT NULL DEFAULT '1', \`points\` int NOT NULL DEFAULT '0', \`refreshToken\` varchar(255) NULL, \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), \`updatedAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP, \`dailyChatCount\` int NULL DEFAULT '3', \`reportedCount\` int NOT NULL DEFAULT '0', \`escrowPoints\` int NOT NULL DEFAULT '0', \`isSuspended\` tinyint NOT NULL DEFAULT 0, \`suspendedUntil\` datetime NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_reported\` (\`id\` int NOT NULL AUTO_INCREMENT, \`reporterId\` int NOT NULL, \`reportedUserId\` int NOT NULL, \`reportType\` enum ('SPAM', 'HARASS', 'FRAUD', 'SCAM', 'ETC') NOT NULL, \`reportDetail\` text NULL, \`status\` enum ('PENDING', 'COMPLETED', 'REJECTED') NOT NULL DEFAULT 'PENDING', \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), \`updatedAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_report_history\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`point_package\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`description\` varchar(255) NOT NULL, \`pointCharge\` int NOT NULL, \`requireCash\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notice\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`content\` text NOT NULL, \`category\` varchar(255) NULL, \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), \`updatedAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`point_ledger\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`type\` enum ('CALL_HOLD', 'CALL_CAPTURE', 'CALL_REFUND', 'CALL_EARN') NOT NULL, \`amount\` int NOT NULL, \`callSessionId\` varchar(255) NOT NULL, \`idempotencyKey\` varchar(255) NOT NULL, \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), UNIQUE INDEX \`IDX_634a1b339541bee23413b7976c\` (\`idempotencyKey\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`match_ticket\` (\`id\` varchar(36) NOT NULL, \`userId\` int NOT NULL, \`status\` enum ('WAITING', 'MATCHED', 'CANCELED', 'EXPIRED') NOT NULL DEFAULT 'WAITING', \`region\` varchar(255) NOT NULL, \`billingType\` enum ('FREE', 'POINTS') NOT NULL, \`cost\` int NULL, \`refunded\` tinyint NOT NULL DEFAULT 0, \`roomId\` varchar(36) NULL, \`matchSessionId\` varchar(36) NULL, \`expiresAt\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`match_session\` (\`id\` varchar(36) NOT NULL, \`userAId\` int NOT NULL, \`userBId\` int NOT NULL, \`region\` varchar(50) NULL, \`roomId\` varchar(36) NULL, \`status\` enum ('ACTIVE', 'ENDED', 'ABORTED') NOT NULL DEFAULT 'ACTIVE', \`startedAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), \`endedAt\` datetime NULL, \`endReason\` enum ('USER_LEFT', 'TIMEOUT', 'BLOCKED', 'REPORTED', 'ERROR') NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`call_session\` (\`id\` varchar(36) NOT NULL, \`matchSessionId\` varchar(255) NOT NULL, \`callerId\` int NOT NULL, \`calleeId\` int NOT NULL, \`status\` enum ('RINGING', 'ONGOING', 'DECLINED', 'ENDED', 'TIMEOUT') NOT NULL, \`startedAt\` datetime NULL, \`endedAt\` datetime NULL, \`lastBilledAt\` datetime NULL, \`heldTotal\` int NOT NULL DEFAULT '0', \`capturedTotal\` int NOT NULL DEFAULT '0', \`earnedTotal\` int NOT NULL DEFAULT '0', \`settledAt\` datetime NULL, \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), INDEX \`IDX_877b596a17b4528cf7e57764dd\` (\`matchSessionId\`, \`status\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`call_participant\` (\`id\` int NOT NULL AUTO_INCREMENT, \`callSessionId\` varchar(255) NOT NULL, \`userId\` int NOT NULL, \`state\` enum ('INVITED', 'JOINED', 'LEFT') NOT NULL DEFAULT 'INVITED', \`lastSeenAt\` datetime NULL, UNIQUE INDEX \`IDX_9959df904e5850700987c87b38\` (\`callSessionId\`, \`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`faq\` (\`id\` int NOT NULL AUTO_INCREMENT, \`question\` varchar(255) NOT NULL, \`answer\` text NOT NULL, \`categoryId\` int NOT NULL, \`createdAt\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`faq_category\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`club_schedule\` ADD CONSTRAINT \`FK_d356ff8a0596a43f493e0e3a726\` FOREIGN KEY (\`clubId\`) REFERENCES \`club\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`club_schedule\` ADD CONSTRAINT \`FK_e6563d34c434f11ce5921503394\` FOREIGN KEY (\`categoryId\`) REFERENCES \`category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`club_schedule_member\` ADD CONSTRAINT \`FK_6e2c44d47cc050ca8e3146941db\` FOREIGN KEY (\`scheduleId\`) REFERENCES \`club_schedule\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`club_schedule_member\` ADD CONSTRAINT \`FK_8550f0785ff8b65c61b430220a8\` FOREIGN KEY (\`memberId\`) REFERENCES \`club_member\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`club_member\` ADD CONSTRAINT \`FK_1047687a2fa4d8aa55ce9ff46ad\` FOREIGN KEY (\`clubId\`) REFERENCES \`club\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`club_member\` ADD CONSTRAINT \`FK_ba6f4421c170b49f0ca6ea52720\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`club_ban_member\` ADD CONSTRAINT \`FK_47b72a455a98bd0453a1e302f1a\` FOREIGN KEY (\`clubId\`) REFERENCES \`club\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`club_ban_member\` ADD CONSTRAINT \`FK_dc28d5b6af96d8477357733605d\` FOREIGN KEY (\`banUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`club_chat_room_member\` ADD CONSTRAINT \`FK_1c8c1287f41699b3d823fe0a93a\` FOREIGN KEY (\`roomId\`) REFERENCES \`club_chat_room\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`club_chat_room\` ADD CONSTRAINT \`FK_b716ed147dbf0665cee7e15ab3f\` FOREIGN KEY (\`clubId\`) REFERENCES \`club\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`club\` ADD CONSTRAINT \`FK_9ac3fe57cb5b546a8854ad5cfad\` FOREIGN KEY (\`leaderId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`club\` ADD CONSTRAINT \`FK_ddd178968da817f697093a01ad6\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`club\` ADD CONSTRAINT \`FK_9cdc83fdaeed12a5f7d9dd0d35e\` FOREIGN KEY (\`categoryId\`) REFERENCES \`category\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comment_like\` ADD CONSTRAINT \`FK_a253dba95eab8659c027bbace44\` FOREIGN KEY (\`commentId\`) REFERENCES \`comment\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comment_like\` ADD CONSTRAINT \`FK_b5a2fc7a9a2b6bcc8c74f6fbb8b\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comment\` ADD CONSTRAINT \`FK_94a85bb16d24033a2afdd5df060\` FOREIGN KEY (\`postId\`) REFERENCES \`post\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comment\` ADD CONSTRAINT \`FK_c0354a9a009d3bb45a08655ce3b\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comment\` ADD CONSTRAINT \`FK_73aac6035a70c5f0313c939f237\` FOREIGN KEY (\`parentCommentId\`) REFERENCES \`comment\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_like\` ADD CONSTRAINT \`FK_789b3f929eb3d8760419f87c8a9\` FOREIGN KEY (\`postId\`) REFERENCES \`post\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_like\` ADD CONSTRAINT \`FK_909fc474ef645901d01f0cc0662\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_saved\` ADD CONSTRAINT \`FK_68c446b5395068f86930a51766a\` FOREIGN KEY (\`postId\`) REFERENCES \`post\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post_saved\` ADD CONSTRAINT \`FK_c1813accf0f3e3a470935600f96\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post\` ADD CONSTRAINT \`FK_1077d47e0112cad3c16bbcea6cd\` FOREIGN KEY (\`categoryId\`) REFERENCES \`category\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`post\` ADD CONSTRAINT \`FK_5c1cf55c308037b5aca1038a131\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`senior_content\` ADD CONSTRAINT \`FK_b547c584a965af2656ea3570c75\` FOREIGN KEY (\`adminId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`senior_content\` ADD CONSTRAINT \`FK_0ff09f220e267355800458a1768\` FOREIGN KEY (\`categoryId\`) REFERENCES \`category\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`point_history\` ADD CONSTRAINT \`FK_5da985b41910fbd9ce8304f389e\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_room_user\` ADD CONSTRAINT \`FK_865761fa2dab5f92440642b16b5\` FOREIGN KEY (\`roomId\`) REFERENCES \`chat_room\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_room_user\` ADD CONSTRAINT \`FK_3155383fce6253c78703f7bae63\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_suspension\` ADD CONSTRAINT \`FK_d8f1bc4d2ab947e208a5c7bf995\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_reported\` ADD CONSTRAINT \`FK_e7b7fc17dd55d79b5a67c52275b\` FOREIGN KEY (\`reporterId\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_reported\` ADD CONSTRAINT \`FK_4a60f409df4f79b8ff1c22afa28\` FOREIGN KEY (\`reportedUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`match_ticket\` ADD CONSTRAINT \`FK_536d378e897aa11fb492bee6f08\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`faq\` ADD CONSTRAINT \`FK_89ec0666829fad019cdf0dcac22\` FOREIGN KEY (\`categoryId\`) REFERENCES \`category\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`faq\` DROP FOREIGN KEY \`FK_89ec0666829fad019cdf0dcac22\``);
        await queryRunner.query(`ALTER TABLE \`match_ticket\` DROP FOREIGN KEY \`FK_536d378e897aa11fb492bee6f08\``);
        await queryRunner.query(`ALTER TABLE \`user_reported\` DROP FOREIGN KEY \`FK_4a60f409df4f79b8ff1c22afa28\``);
        await queryRunner.query(`ALTER TABLE \`user_reported\` DROP FOREIGN KEY \`FK_e7b7fc17dd55d79b5a67c52275b\``);
        await queryRunner.query(`ALTER TABLE \`user_suspension\` DROP FOREIGN KEY \`FK_d8f1bc4d2ab947e208a5c7bf995\``);
        await queryRunner.query(`ALTER TABLE \`chat_room_user\` DROP FOREIGN KEY \`FK_3155383fce6253c78703f7bae63\``);
        await queryRunner.query(`ALTER TABLE \`chat_room_user\` DROP FOREIGN KEY \`FK_865761fa2dab5f92440642b16b5\``);
        await queryRunner.query(`ALTER TABLE \`point_history\` DROP FOREIGN KEY \`FK_5da985b41910fbd9ce8304f389e\``);
        await queryRunner.query(`ALTER TABLE \`senior_content\` DROP FOREIGN KEY \`FK_0ff09f220e267355800458a1768\``);
        await queryRunner.query(`ALTER TABLE \`senior_content\` DROP FOREIGN KEY \`FK_b547c584a965af2656ea3570c75\``);
        await queryRunner.query(`ALTER TABLE \`post\` DROP FOREIGN KEY \`FK_5c1cf55c308037b5aca1038a131\``);
        await queryRunner.query(`ALTER TABLE \`post\` DROP FOREIGN KEY \`FK_1077d47e0112cad3c16bbcea6cd\``);
        await queryRunner.query(`ALTER TABLE \`post_saved\` DROP FOREIGN KEY \`FK_c1813accf0f3e3a470935600f96\``);
        await queryRunner.query(`ALTER TABLE \`post_saved\` DROP FOREIGN KEY \`FK_68c446b5395068f86930a51766a\``);
        await queryRunner.query(`ALTER TABLE \`post_like\` DROP FOREIGN KEY \`FK_909fc474ef645901d01f0cc0662\``);
        await queryRunner.query(`ALTER TABLE \`post_like\` DROP FOREIGN KEY \`FK_789b3f929eb3d8760419f87c8a9\``);
        await queryRunner.query(`ALTER TABLE \`comment\` DROP FOREIGN KEY \`FK_73aac6035a70c5f0313c939f237\``);
        await queryRunner.query(`ALTER TABLE \`comment\` DROP FOREIGN KEY \`FK_c0354a9a009d3bb45a08655ce3b\``);
        await queryRunner.query(`ALTER TABLE \`comment\` DROP FOREIGN KEY \`FK_94a85bb16d24033a2afdd5df060\``);
        await queryRunner.query(`ALTER TABLE \`comment_like\` DROP FOREIGN KEY \`FK_b5a2fc7a9a2b6bcc8c74f6fbb8b\``);
        await queryRunner.query(`ALTER TABLE \`comment_like\` DROP FOREIGN KEY \`FK_a253dba95eab8659c027bbace44\``);
        await queryRunner.query(`ALTER TABLE \`club\` DROP FOREIGN KEY \`FK_9cdc83fdaeed12a5f7d9dd0d35e\``);
        await queryRunner.query(`ALTER TABLE \`club\` DROP FOREIGN KEY \`FK_ddd178968da817f697093a01ad6\``);
        await queryRunner.query(`ALTER TABLE \`club\` DROP FOREIGN KEY \`FK_9ac3fe57cb5b546a8854ad5cfad\``);
        await queryRunner.query(`ALTER TABLE \`club_chat_room\` DROP FOREIGN KEY \`FK_b716ed147dbf0665cee7e15ab3f\``);
        await queryRunner.query(`ALTER TABLE \`club_chat_room_member\` DROP FOREIGN KEY \`FK_1c8c1287f41699b3d823fe0a93a\``);
        await queryRunner.query(`ALTER TABLE \`club_ban_member\` DROP FOREIGN KEY \`FK_dc28d5b6af96d8477357733605d\``);
        await queryRunner.query(`ALTER TABLE \`club_ban_member\` DROP FOREIGN KEY \`FK_47b72a455a98bd0453a1e302f1a\``);
        await queryRunner.query(`ALTER TABLE \`club_member\` DROP FOREIGN KEY \`FK_ba6f4421c170b49f0ca6ea52720\``);
        await queryRunner.query(`ALTER TABLE \`club_member\` DROP FOREIGN KEY \`FK_1047687a2fa4d8aa55ce9ff46ad\``);
        await queryRunner.query(`ALTER TABLE \`club_schedule_member\` DROP FOREIGN KEY \`FK_8550f0785ff8b65c61b430220a8\``);
        await queryRunner.query(`ALTER TABLE \`club_schedule_member\` DROP FOREIGN KEY \`FK_6e2c44d47cc050ca8e3146941db\``);
        await queryRunner.query(`ALTER TABLE \`club_schedule\` DROP FOREIGN KEY \`FK_e6563d34c434f11ce5921503394\``);
        await queryRunner.query(`ALTER TABLE \`club_schedule\` DROP FOREIGN KEY \`FK_d356ff8a0596a43f493e0e3a726\``);
        await queryRunner.query(`DROP TABLE \`faq_category\``);
        await queryRunner.query(`DROP TABLE \`faq\``);
        await queryRunner.query(`DROP INDEX \`IDX_9959df904e5850700987c87b38\` ON \`call_participant\``);
        await queryRunner.query(`DROP TABLE \`call_participant\``);
        await queryRunner.query(`DROP INDEX \`IDX_877b596a17b4528cf7e57764dd\` ON \`call_session\``);
        await queryRunner.query(`DROP TABLE \`call_session\``);
        await queryRunner.query(`DROP TABLE \`match_session\``);
        await queryRunner.query(`DROP TABLE \`match_ticket\``);
        await queryRunner.query(`DROP INDEX \`IDX_634a1b339541bee23413b7976c\` ON \`point_ledger\``);
        await queryRunner.query(`DROP TABLE \`point_ledger\``);
        await queryRunner.query(`DROP TABLE \`notice\``);
        await queryRunner.query(`DROP TABLE \`point_package\``);
        await queryRunner.query(`DROP TABLE \`user_report_history\``);
        await queryRunner.query(`DROP TABLE \`user_reported\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`user_suspension\``);
        await queryRunner.query(`DROP TABLE \`chat_room_user\``);
        await queryRunner.query(`DROP TABLE \`chat_room\``);
        await queryRunner.query(`DROP TABLE \`point_history\``);
        await queryRunner.query(`DROP TABLE \`senior_content\``);
        await queryRunner.query(`DROP TABLE \`post\``);
        await queryRunner.query(`DROP TABLE \`post_saved\``);
        await queryRunner.query(`DROP TABLE \`post_like\``);
        await queryRunner.query(`DROP TABLE \`comment\``);
        await queryRunner.query(`DROP TABLE \`comment_like\``);
        await queryRunner.query(`DROP INDEX \`IDX_4bb3fbb86fb58fe2de057ea32a\` ON \`category\``);
        await queryRunner.query(`DROP TABLE \`category\``);
        await queryRunner.query(`DROP TABLE \`club\``);
        await queryRunner.query(`DROP TABLE \`club_chat_room\``);
        await queryRunner.query(`DROP TABLE \`club_chat_room_member\``);
        await queryRunner.query(`DROP TABLE \`club_ban_member\``);
        await queryRunner.query(`DROP TABLE \`club_member\``);
        await queryRunner.query(`DROP TABLE \`club_schedule_member\``);
        await queryRunner.query(`DROP TABLE \`club_schedule\``);
    }

}
